// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b4ecdcaa-83ed-451d-b4f9-cf16854d8720",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_JtmkDiax0",
    "aws_user_pools_web_client_id": "712fmf5okrk4cgrm1eoroacut2",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://l3poy2lszvbnxcgyh3gvdv24iy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "predictions": {
        "convert": {
            "transcription": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "language": "en-US"
                }
            },
            "speechGenerator": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "VoiceId": "Kendra",
                    "LanguageCode": "en-US"
                }
            }
        }
    }
};


export default awsmobile;
